FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
        python3 \
        python3-pip

ADD . /delivery_portal

WORKDIR /delivery_portal

RUN pip3 install -r requirements.txt

CMD ["python3", "deliv_portal.py"]
