# Set official image -- parent image
FROM python:latest

# Cope the requirements file to the current location
COPY ./dds/requirements.txt /requirements.txt

# Set as development environment
ENV FLASK_ENV development

# Install all dependencies
RUN pip3 install -r /requirements.txt

# Make a code directory
RUN mkdir /code

# Set working directory
WORKDIR /code/dds

# Run app
CMD ["python3", "app.py"]
