# Set official image -- parent image
FROM python:latest

# Copy the requirements file to the current location in container
COPY requirements.txt /requirements.txt

# Set as development environment
ENV FLASK_ENV development
ENV SECRET_KEY mysecretkey
ENV SQLALCHEMY_DATABASE_URI mysql+pymysql://apiuser:apipass@db/DeliverySystem
ENV PYTHONPATH /code

# Install all dependencies
RUN pip3 install -r /requirements.txt

# Make a code directory in container
RUN mkdir /code

# Set working directory - 'code' dir in container, 'code' dir locally (in code)
WORKDIR /code/code_dds

# Run app -- needs to be in WORKDIR
CMD ["python3", "app.py"]
