# Set official image -- parent image
FROM python:latest

# Copy the requirements file to the current location in container
COPY requirements.txt /requirements.txt

# Install some necessary systems packages
RUN apt-get update
RUN apt-get install -y gfortran libopenblas-dev liblapack-dev

# Install all dependencies
RUN pip3 install -r /requirements.txt
RUN pip3 install gunicorn

# Make a code directory in container
RUN mkdir /code

# Add code directory in pythonpath
ENV PYTHONPATH /code

# Add parameters for gunicorn
ENV GUNICORN_CMD_ARGS "--bind=0.0.0.0:5000 --workers=2 --thread=4 --worker-class=gthread --forwarded-allow-ips='*' --access-logfile -"

# Set working directory - 'code' dir in container, 'code' dir locally (in code)
WORKDIR /code/code_dds

# Run app -- needs to be in WORKDIR
CMD ["gunicorn", "app:app"]
