"""add-done-to-project

Revision ID: 02acefb3057a
Revises: 908382be548a
Create Date: 2022-08-17 08:32:57.578324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "02acefb3057a"
down_revision = "908382be548a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("done", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "done")
    # ### end Alembic commands ###
