"""unit_quota_and_warning

Revision ID: 0c9c237cced5
Revises: eb395af90e18
Create Date: 2023-01-10 14:30:57.089391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0c9c237cced5"
down_revision = "eb395af90e18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns
    op.add_column("units", sa.Column("quota", sa.Integer(), nullable=False))
    op.add_column("units", sa.Column("warning_level", sa.Integer(), nullable=False, default=80))

    # Update existing columns
    # 1. Load table - need to load columns in order to use
    unit_table = sa.sql.table("units", sa.sql.column("quota", mysql.INTEGER))
    # 2. Update column value
    op.execute(unit_table.update().values(quota=100 * 1e12))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "warning_level")
    op.drop_column("units", "quota")
    # ### end Alembic commands ###
