"""unit_quota_and_warning

Revision ID: 0c9c237cced5
Revises: eb395af90e18
Create Date: 2023-01-10 14:30:57.089391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c9c237cced5'
down_revision = 'eb395af90e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('quota', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('warning_level', sa.Integer(), nullable=False, default=80))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'warning_level')
    op.drop_column('units', 'quota')
    # ### end Alembic commands ###
