"""unit_contact_email_non_nullable

Revision ID: 0cd0a3b251e0
Revises: 3d610b382383
Create Date: 2024-12-03 10:51:34.143028

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0cd0a3b251e0"
down_revision = "3d610b382383"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "units",
        "contact_email",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
        server_default="delivery@scilifelab.se",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "units", "contact_email", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###
