"""add_password_reset

Revision ID: 1256117ad629
Revises: 666003748d14
Create Date: 2022-03-14 16:23:44.287254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1256117ad629"
down_revision = "666003748d14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_resets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("issued", sa.DateTime(), nullable=False),
        sa.Column("changed", sa.DateTime(), nullable=True),
        sa.Column("valid", mysql.TINYINT(display_width=1), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("password_resets")
    # ### end Alembic commands ###
