"""remove-cost-from-usage-table

Revision ID: 21f683dcd2b1
Revises: f27c5988d640
Create Date: 2023-10-05 13:47:11.852359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21f683dcd2b1'
down_revision = 'f27c5988d640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage', 'cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('cost', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
