"""add_num_unique_proj_owners

Revision ID: 53bb37a3cd84
Revises: 93ec6983ce8d
Create Date: 2023-05-30 13:24:52.406907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "53bb37a3cd84"
down_revision = "93ec6983ce8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reporting", sa.Column("project_owner_unique_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reporting", "project_owner_unique_count")
    # ### end Alembic commands ###
