"""add-busy-to-project

Revision ID: 6e9b74878553
Revises: 02acefb3057a
Create Date: 2022-09-07 09:09:06.081829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e9b74878553'
down_revision = '02acefb3057a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('busy', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'busy')
    # ### end Alembic commands ###
