"""removing_project-invites

Revision ID: 83e1dd4ddd7e
Revises: e5a51e5ed9a1
Create Date: 2022-02-18 13:14:00.863907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "83e1dd4ddd7e"
down_revision = "e5a51e5ed9a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projectinvites")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projectinvites",
        sa.Column(
            "project_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
        ),
        sa.Column(
            "invite_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
        ),
        sa.Column("owner", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["invite_id"], ["invites.id"], name="projectinvites_ibfk_1", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="projectinvites_ibfk_2", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id", "invite_id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "apscheduler_jobs",
        sa.Column("id", mysql.VARCHAR(length=191), nullable=False),
        sa.Column("next_run_time", mysql.DOUBLE(asdecimal=True), nullable=True),
        sa.Column("job_state", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_apscheduler_jobs_next_run_time", "apscheduler_jobs", ["next_run_time"], unique=False
    )
    # ### end Alembic commands ###
