"""add_column_active_to_motd
Revision ID: 908382be548a
Revises: cd1903e5f2b0
Create Date: 2022-06-13 12:34:34.981373
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "908382be548a"
down_revision = "cd1903e5f2b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("motd", sa.Column("active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("motd", "active")
    # ### end Alembic commands ###