"""busy-property-and-altering-downloading-columns

Revision ID: 98c334b1c089
Revises: eb395af90e18
Create Date: 2022-10-06 06:58:14.411709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98c334b1c089'
down_revision = 'eb395af90e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('busy_downloading', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('busy_altering', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'busy_altering')
    op.drop_column('projects', 'busy_downloading')
    # ### end Alembic commands ###
