"""changed_sensitive

Revision ID: a5a40d843415
Revises: d117e6299dc9
Create Date: 2022-02-19 10:32:31.626236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a5a40d843415"
down_revision = "d117e6299dc9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("non_sensitive", sa.Boolean(), nullable=True))
    op.drop_column("projects", "is_sensitive")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "is_sensitive", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("projects", "non_sensitive")
    op.create_table(
        "apscheduler_jobs",
        sa.Column("id", mysql.VARCHAR(length=191), nullable=False),
        sa.Column("next_run_time", mysql.DOUBLE(asdecimal=True), nullable=True),
        sa.Column("job_state", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_apscheduler_jobs_next_run_time", "apscheduler_jobs", ["next_run_time"], unique=False
    )
    # ### end Alembic commands ###
