"""tb_uploaded_since_start_added

Revision ID: aec752f1e0a5
Revises: d48ecb4db259
Create Date: 2023-05-31 14:09:07.327919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "aec752f1e0a5"
down_revision = "d48ecb4db259"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reporting", sa.Column("tb_uploaded_since_start", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reporting", "tb_uploaded_since_start")
    # ### end Alembic commands ###
