"""create_bucket_items

Revision ID: af460829312f
Revises: 666003748d14
Create Date: 2022-03-07 10:08:46.585236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.orm.session import Session
from dds_web.database import models

# revision identifiers, used by Alembic.
revision = "af460829312f"
down_revision = "666003748d14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bucketitems",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("part", sa.Integer(), nullable=False),
        sa.Column("name_in_bucket", sa.Text(), nullable=False),
        sa.Column("active_file", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["active_file"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    session = Session(bind=op.get_bind())
    all_files = session.query(models.File).all()
    for file in all_files:
        new_bucket_item = models.BucketItem(part=1, name_in_bucket=file.name_in_bucket)
        file.bucket_items.append(new_bucket_item)
    session.commit()
    op.drop_column("files", "name_in_bucket")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("name_in_bucket", mysql.TEXT(), nullable=False))

    session = Session(bind=op.get_bind())
    all_files = session.query(models.File).all()
    for file in all_files:
        for x in file.bucket_items:
            # Only uses the first, need to look into how to handle downgrade better
            file.name_in_bucket = x.name_in_bucket
            break
    session.commit()

    op.drop_table("bucketitems")
    # ### end Alembic commands ###
