"""add-reporting-table

Revision ID: b976f6cda95c
Revises: 0c9c237cced5
Create Date: 2023-01-26 10:02:37.535695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b976f6cda95c"
down_revision = "0c9c237cced5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reporting",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("unit_count", sa.Integer(), nullable=False),
        sa.Column("researchuser_count", sa.Integer(), nullable=False),
        sa.Column("unituser_count", sa.Integer(), nullable=False),
        sa.Column("superadmin_count", sa.Integer(), nullable=False),
        sa.Column("total_user_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reporting")
    # ### end Alembic commands ###
