"""total_number_of_projects_added

Revision ID: c1e908241401
Revises: 879b99e7f212
Create Date: 2023-05-29 11:27:10.843043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1e908241401'
down_revision = '879b99e7f212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reporting', sa.Column('total_project_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reporting', 'total_project_count')
    # ### end Alembic commands ###
