"""sensitive_not_nullable

Revision ID: c3d3e960fc1b
Revises: a5a40d843415
Create Date: 2022-02-19 10:34:15.584075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c3d3e960fc1b"
down_revision = "a5a40d843415"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apscheduler_jobs",
        sa.Column("id", mysql.VARCHAR(length=191), nullable=False),
        sa.Column("next_run_time", mysql.DOUBLE(asdecimal=True), nullable=True),
        sa.Column("job_state", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_apscheduler_jobs_next_run_time", "apscheduler_jobs", ["next_run_time"], unique=False
    )
    # ### end Alembic commands ###
