"""remove_project-invites

Revision ID: d117e6299dc9
Revises: e5a51e5ed9a1
Create Date: 2022-02-18 14:43:43.954122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d117e6299dc9"
down_revision = "e5a51e5ed9a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projectinvites")
    op.add_column(
        "projectinvitekeys", sa.Column("owner", mysql.TINYINT(display_width=1), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projectinvitekeys", "owner")
    op.create_table(
        "projectinvites",
        sa.Column(
            "project_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
        ),
        sa.Column(
            "invite_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
        ),
        sa.Column("owner", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["invite_id"], ["invites.id"], name="projectinvites_ibfk_1", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="projectinvites_ibfk_2", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id", "invite_id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
