"""add_terrabytes_stored_in_system

Revision ID: d48ecb4db259
Revises: 53bb37a3cd84
Create Date: 2023-05-30 13:44:05.232573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d48ecb4db259"
down_revision = "53bb37a3cd84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reporting", sa.Column("tb_stored_now", sa.Float, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reporting", "tb_stored_now")
    # ### end Alembic commands ###
