"""add_unit_admin

Revision ID: e07c83ed0bda
Revises: 879b99e7f212
Create Date: 2023-05-29 09:09:24.689422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e07c83ed0bda"
down_revision = "879b99e7f212"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reporting", sa.Column("unit_admin_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reporting", "unit_admin_count")
    # ### end Alembic commands ###
