# Lychee: Verify links in MD files
---
name: Linkspector
on:
  push:
    branches: [dev, master]
    paths: &markdown
      - "**/*.md"
  pull_request:
    paths: *markdown
  schedule:
    - cron: "0 1 * * *" # every day at 1am
permissions:
  pull-requests: write
jobs:
  check-links:
    name: runner / lychee
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --scheme https --scheme http --accept 401,403 '**/*.md'
          fail: false
          token: ${{ secrets.github_token }}
