# Prettier: Format code.
# Prettier is a code formatter. We mostly use it for the markdown files.
# https://prettier.io/
# ---
# Action failing? Run npx prettier --write . locally to execute formatting.
---
name: Prettier
on: [push, pull_request]

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier --check
        run: prettier --check ${GITHUB_WORKSPACE}
