# Lint Python - Black
# This action lints python using black - a python code formatter.
# https://github.com/psf/black
# This does not format the code, this only detects and informs on issues.
# To format with black, run `black .` locally in the repository.
name: Lint Python
on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:
  PythonLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check code lints with Black
        uses: psf/black@stable
