# Add line to end of sprintlog
# pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
# - name: Commit and push changes
# run: |
# git config user.name github-actions
# git config user.email github-actions@github.com
# git add .
# git commit -m "new line to sprintlog"
# git push
---
name: Sprintlog
on:
  pull_request:
    types: [opened, reopened]
env:
  FILE_TO_UPDATE: "SPRINTLOG.md"
jobs:
  Sprintlog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Modify sprintlog
        run: |
          echo "- ${{ github.event.pull_request.title }}" >> ${FILE_TO_UPDATE}

      - name: Commit & push changes
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add --all
          git commit -S -a -m "New line to ${FILE_TO_UPDATE}"
          git push
